### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by maxbambi** [MRLB/kodi-eurosportplayer#4]
This plugin is only in German, even if it is working also with eurosportplayer of other countries (I have tried this in Italy) 
Could I help you to cut string from code and allow localization?

**Comment by MRLB** [comment]
Please try new version (Kodi 19-version)

**Comment by maxbambi** [comment]
@MRLB 
I pasted cookie in new version, but I get an error. What is the right format to input cookie?

**Comment by MRLB** [comment]
What error message do you get?
I've put my Cookie into line 38 of the settings.xml (The same cookie as in the kodi 18 version)

**Comment by maxbambi** [comment]
@MRLB 
I don't know what happened... Now it is working...
May I post you italian strings?

**Comment by MRLB** [comment]
yes of course
I saw that discovery was adding a new key to the stream. I have to check how I can implement this.
https://discovery-eur.conax.cloud/fairplay/clearkey

**Comment by maxbambi** [comment]
@MRLB 
I have made a pull request for italian strings.
