### ISSUE TITLE
Kodi Matrix

### ISSUE THREAD

**Issue by hyperion-ak** [MRLB/kodi-eurosportplayer#5]
Hi MRLB, thank you for creating such a nice eurosport plugin! Kodi Matrix moved to stabile recently, I forget and updated the project code to work under Kodi Matrix. Some files such as settings.xml still have to be updated. My knowledge of python is limited, please feel free to update and improve the code appropriately.

**Comment by MRLB** [comment]
Thanks. Looks nice

**Comment by MRLB** [comment]
Unfortunatelly you have updated a outdated version. Therefore I did it on the current version one more time.
